### ISSUE TITLE
存在sql错误

### ISSUE THREAD

**Issue by hatmony** [PatchouliTC/MasterDuelSimpleTranslateTool#3]
先十分感谢大佬开发的工具！
master_duel_main.py和master_duel_manual_version.py里的sql有错误

conn.execute(f"INSERT INTO CaGrdDhash (code,dhash) VALUES ('{_file_name}', '{_temp_dhash}' )");

CaGrdDhash 表误打了

**Comment by PatchouliTC** [comment]
tks,我一直以为我昨天已经修完了
